"""add otp infra and update users

Revision ID: 276c50f2d14e
Revises: bcdfcf9efcc8
Create Date: 2026-02-11 22:40:54.351280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '276c50f2d14e'
down_revision: Union[str, Sequence[str], None] = 'bcdfcf9efcc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
